### PR TITLE
use just for CI

### PR DESCRIPTION
**Pull request by kbknapp**
This PR uses `just` for CI instead of manual commands. This means it's easier to keep the local workflow and the CI workflow (to include release workflows) in sync.

For example running `just ci` should be _exactly_ the same as what happens in CI (mod CI trying to be smart about what it checks to save time).

### CODE REVIEW

**Comment by kbknapp** [comment]
Current dependencies on/for this PR:
* main
  * **PR #257** <a href="https://app.graphite.dev/github/pr/seaplane-io/seaplane/257" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/seaplane-io/seaplane/257?utm_source=stack-comment).

**Review by ericsampson — APPROVED** [review]
Love it.

The main repo README links to "see CONTRIBUTING.MD for instructions", but that page doesn't exist yet 😅 
because it would be nice to have a little instruction for people there on how to build/test/run it themselves, using the new `just` recipes.

**Review by RafalGoslawski — APPROVED** [review]
LGTM

**Comment by kbknapp** [comment]
> The main repo README links to "see CONTRIBUTING.MD for instructions", but that page doesn't exist yet

Ah that's a bad link then, because [it does exist](https://github.com/seaplane-io/seaplane/blob/main/docs/CONTRIBUTING.md) 😄

**Pull request merged**
