### PR TITLE
Amend Locks Info Field Name in CLI and SDKs

### PR DESCRIPTION
**Pull request by joshua-sp**
## Purpose of change

Aligns SDKs and CLI with changed API field name so that it works.

## Description of change

- Amends field name in various SDKs
- Bumps the version on them and adds to changelog

## Notes
- CLI changes in separate PR as it can't pass CI until this is merged and pushed to crates repo
- Once this is merged, Toni has said he'll push the SDK packages to their repos

### CODE REVIEW

**Review by kbknapp — APPROVED** [review]
Please bump the Rust SDK to v0.4.0 before merging.

**Comment by joshua-sp** [comment]
Thanks! Rebase shenanigans.
I want a VC that recognises my commit as "added 0.1 to the version number" rather than "changed this text to 0.3" :)

**Comment by joshua-sp** [comment]
Hm @kbknapp Is it expected that the CI for this should be looking at the deps for the CLI as well?

From https://github.com/seaplane-io/seaplane/actions/runs/3940611749/jobs/6741942907
```
Run just lint-sdk-rust
typos
cargo fmt --manifest-path crates/container-image-ref/Cargo.toml --check
cargo fmt --manifest-path seaplane-sdk/rust/Cargo.toml --check
cargo clippy  --manifest-path seaplane-sdk/rust/Cargo.toml --all-targets -- -D warnings
error: failed to select a version for the requirement `seaplane = "^0.3.0"`
candidate versions found which didn't match: 0.4.0
location searched: /home/runner/actions-runner/_work/seaplane/seaplane/seaplane-sdk/rust
required by package `seaplane-cli v0.4.0 (/home/runner/actions-runner/_work/seaplane/seaplane/seaplane-cli)`
error: Recipe `_lint-rust-crate` failed on line 1[9](https://github.com/seaplane-io/seaplane/actions/runs/3940611749/jobs/6741942907#step:7:10)7 with exit code [10](https://github.com/seaplane-io/seaplane/actions/runs/3940611749/jobs/6741942907#step:7:11)1
Error: Process completed with exit code 101.
```

Or is the expectation in the repo that all Rust SDK and CLI changes should be bundled together in one PR in order for this not to happen?
I am fine with that, I just thought a flow of: SDK PR -> Push packages to crates etc -> CLI PR makes the most sense

**Comment by kbknapp** [comment]
Yeah we'll have to push the v0.4.0 SDK to crates.io then do any CLI changes required. I think the CLI CI is getting picked up because of the file change in the `seaplane-cli/` dir?

**Comment by joshua-sp** [comment]
Hm, I've removed the change and still seems to be getting CLI involved for some reason 🤔 

```
cargo test  --manifest-path seaplane-sdk/rust/Cargo.toml
error: failed to select a version for the requirement `seaplane = "^0.3.0"`
candidate versions found which didn't match: 0.4.0
location searched: /home/runner/actions-runner/_work/seaplane/seaplane/seaplane-sdk/rust
required by package `seaplane-cli v0.4.0 (/home/runner/actions-runner/_work/seaplane/seaplane/seaplane-cli)`
```

Even with the manifest path set, it still seems to be somehow aware of the CLIs dep being missing!

**Comment by joshua-sp** [comment]
Ah, I think this is because they share a cargo workspace

https://doc.rust-lang.org/cargo/reference/workspaces.html
> When inside a subdirectory within the workspace, Cargo will automatically search the parent directories for a Cargo.toml file with a [workspace] definition to determine which workspace to use. The [package.workspace](https://doc.rust-lang.org/cargo/reference/manifest.html#the-workspace-field) manifest key can be used in member crates to point at a workspace's root to override this automatic search. The manual setting can be useful if the member is not inside a subdirectory of the workspace root.

It doesn't seem like there's a "don't recurse to look for a workspace" flag, so I think the only options are either to:
1. Remove the workspace and fix whatever issues that causes
1. Bundle CLI and SDK changes into one PR

@kbknapp  you got a preference for which?

**Comment by kbknapp** [comment]
I believe it's the `path = ...` that is causing issues here. We can remove that and just go with the version.

**Pull request merged**
