### PR TITLE
Swap processor code to use updated version from PDK

### PR DESCRIPTION
**Pull request by joshua-sp**
This swaps out the previously "vendored" processor code for a proper upstream dependency on the PDK.
Now we can version it properly.

Of note:
The processor code at time of writing is different to what was removed here, however it's designed to be backwards compatible. This unlocks the ability to use the new metadata format for Carrier, which will be useful in designing endpoints-api compatible flows.

### CODE REVIEW

**Review by tonilopezmr — APPROVED** [review]
🚀

**Comment by joshua-sp** [comment]
Okay, I've deployed an App with a beta version that uses this branch, and it appears to be working as expected:

```
$ curl https://carrier.staging.cplane.dev/apps/joshua-beta10-test-app-00/latest/hello -H "Content-Type: application/json" -H "$(tks)" -d '{ "input": [{"another-name": "test1"}, {"one-more-name": "test2"}] }' 
{"id":"c7f9e271-28b0-4bcb-8a48-52bd08908090","status":"processing"}
$ curl https://carrier.staging.cplane.dev/apps/joshua-beta10-test-app-00/latest/hello/request/c7f9e271-28b0-4bcb-8a48-52bd08908090 -H "$(tks)"
{"id":"c7f9e271-28b0-4bcb-8a48-52bd08908090","output":["hello world c7f9e271-28b0-4bcb-8a48-52bd08908090","hello world c7f9e271-28b0-4bcb-8a48-52bd08908090"],"status":"completed"}
```

@tonilopezmr Should I amend this branch to be a new version of the SDK proper (i.e: not a beta release), and publish it?

**Comment by tonilopezmr** [comment]
> @tonilopezmr Should I amend this branch to be a new version of the SDK proper (i.e: not a beta release), and publish it? 

I'm working on the next Stable version, should we include this?

**Comment by joshua-sp** [comment]
Yep, sounds good to me.

**Pull request merged**
