### PR TITLE
oid: add schemars support for typed oids

### PR DESCRIPTION
**Pull request by chrisdickinson**
Implement basic schemars support for TypedOid. This adds a "long_name" method to OidPrefix (so we can name the schema "FormationId" instead of "FrmId", e.g.)

This makes working with [aide](https://docs.rs/aide/) possible.

### CODE REVIEW

**Review by kbknapp — APPROVED** [review]
LGTM

**Comment by kbknapp** [comment]
Oh could you bump the minor version too so we can publish the change.

**Comment by chrisdickinson** [comment]
Ooh, thanks, good catch.

**Comment by kbknapp** [comment]
@chrisdickinson I've made the eng team an owner of all of our Rust crates on crates.io so you should be able to `cargo package && cargo publish` inside the `creates/oid/` dir after you merge.

**Pull request merged**
