### PR TITLE
How to publish a new SDK version section in CONTRIBUTING

### PR DESCRIPTION
**Pull request by tonilopezmr**
* How to release a new version of the Python and JS SDKs

@joshua-sp one day did a change to the python SDK, and he asked me how to release the new version. This is the explanation for that answer.

### CODE REVIEW

**Review by tiago-peres — APPROVED** [review]
LGTM

**Comment by kbknapp** [comment]
(I'm still ooo) we don't want expect, or necessarily want the public to push new releases so putting these instructions in the public contributions page probably isn't the best place?

**Comment by tonilopezmr** [comment]
> (I'm still ooo) we don't expect, or necessarily want the public to push new releases so putting these instructions in the public contributions page probably isn't the best place?

I think it is a good idea to have everything in the same place, as long as only Seaplane staff can create tags, everyone can see our deployments here: https://github.com/seaplane-io/seaplane/tags

It can also be in our internal docs, I just wanted to have everything in one place. Also, the new workflows for GitHub action, can be discussed, after you come back @kbknapp. It was just to not block it.

**Comment by tonilopezmr** [comment]
@kbknapp is not here, I'd prefer to block this until @kbknapp is back. Then we can review the last changes together 😄

**Review by joshua-sp — APPROVED** [review]

**Comment by tonilopezmr** [comment]
Really good point! I'm going to add that warning ⚠️

**Review by kbknapp — APPROVED** [review]

**Pull request merged**
