### PR TITLE
fix just workflow on Windows

### PR DESCRIPTION
**Pull request by kbknapp**
This PR fixes the `just` workflow on Windows which wasn't working at all. It also takes advantage of the new recipe attributes in `just`!

### CODE REVIEW

**Comment by kbknapp** [comment]
Current dependencies on/for this PR:
* main
  * **PR #269** <a href="https://app.graphite.dev/github/pr/seaplane-io/seaplane/269" target="_blank">Graphite</a> 
    * **PR #270** <a href="https://app.graphite.dev/github/pr/seaplane-io/seaplane/270" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/seaplane-io/seaplane/270?utm_source=stack-comment).

**Review by Jess3Jane — APPROVED** [review]
Seems like an improvement, going to mostly just trust you that it works

**Review by ericsampson — APPROVED** [review]
We can get rid of the need to worry about installing zip (and mentioning choco) by using the PS cmdlet [Compress-Archive](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7.3)

The Just annotation thing is very cool, you should share info on that technique in Slack for everyone to know!

**Comment by kbknapp** [comment]
> We can get rid of the need to worry about installing zip (and mentioning choco) by using the PS cmdlet [Compress-Archive](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7.3)

Nice! I'll test that out later and put in another PR cause it'd be nice to need fewer external tools 🚀

**Pull request merged**
